[build]
  command = "npm run build"
  publish = "dist" # atau "public", tergantung output folder Anda

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
