[build]
  # Folder tempat file frontend Anda berada
  publish = "public"
  # Folder tempat Netlify Functions Anda berada
  functions = "netlify/functions"

# Konfigurasi spesifik untuk fungsi 'generate-pdf'.
# Ini cara yang lebih eksplisit dan aman untuk mengatur timeout.
[functions."generate-pdf"]
  timeout = 25

[[redirects]]
  # Mengarahkan permintaan dari root ke Netlify Function kita
  from = "/api/generate-pdf"
  to = "/.netlify/functions/generate-pdf"
  status = 200
